models:
  logistic:
    hyperparameters:
      C: [0.1, 1, 10]
      penalty: ['l1', 'l2']
    
  svc:
    hyperparameters:
      C: [0.1, 1, 10]
      kernel: ['linear', 'rbf']
    
  knn:
    hyperparameters:
      n_neighbors: [3, 5, 7]
      weights: ['uniform', 'distance']
    
  kernel_svm:
    hyperparameters:
      C: [0.1, 1, 10]
      kernel: ['rbf', 'poly', 'sigmoid']
    
  naive_bayes:
    hyperparameters:
      var_smoothing: [1e-9, 1e-8, 1e-7]
    
  dt:
    hyperparameters:
      max_depth: [None, 5, 10]
      min_samples_split: [2, 5, 10]
    
  random_forest:
    hyperparameters:
      n_estimators: [100, 200, 300]
      max_depth: [None, 5, 10]
